### ISSUE TITLE
suggestion: make deno install possible

### ISSUE THREAD

**Issue by lucacasonato** [denosaurs/ddoc#1]
It would be really awesome if you could just deno install this project. To make that work there are a few things that could use improvement IMO:

- [ ] download `.deno_plugins` relative to `Deno.mainModule`, `import.meta.url` or a cache folder like `$DENO_DIR/.deno_plugins`. Otherwise a `.deno_plugins` folder gets created everywhere you run the program.
- [ ] embed the contents of the doc_website files in the source code, so that doc_website repo does not need to be cloned and built.  This can probably be done the same way that wasm files are embedded into source code. As compressed base64 strings.

**Comment by notfilippo** [comment]
Thanks for the suggestions, I will open separate PRs to resolve each issue.

**Comment by notfilippo** [comment]
This should be completed as of 7a4e89586393269d9f2d89ca12b0003d98ce2a95.
